### ISSUE TITLE
Wordlists need to be updated to resynch with the official Wordle

### ISSUE THREAD

**Issue by hackerb9** [bgri/m100LE#18]
As of today (August 16, 2022), the word M100LE offers is behind the NYTimes by sixteen days. I believe this is because the NYT removed the most obscure words (like "AGORA") and words which are emotionally charged for some people ("LYNCH", "SLAVE"). Some words were moved to the end of the list ("FETUS").

**Comment by hackerb9** [comment]
It looks like the changes are minor. https://github.com/jackgreenburg/wordle-wordlists

**Comment by bgri** [comment]
Oh! That's interesting... I wasn't aware that someone had done the comparison. Minor for sure.
