### ISSUE TITLE
Fix RAM Directory for 8201 and T102

### ISSUE THREAD

**Issue by hackerb9** [bgri/m100LE#21]
> 8201a ran [RNDACC] without error, though the data displayed when it showed the selected word was incorrect.
> Word one in WL2022.DO should be REBUS.
> ![image](https://user-images.githubusercontent.com/14062627/185451510-5269daa2-9f05-456c-845a-453bc7d9bda1.png)

> And just to see what happens, I ran it on the 102... RNDACC runs, but can't find the file as  'unusual' data is discovered ...  likely due to the offset in line 16 being inaccurate as `PEEK(1)` on the model 102 isn't tested( 167). ![image](https://user-images.githubusercontent.com/14062627/185454470-39e7520b-a717-4f2e-8808-6e64feae2b5a.png)

_Originally posted by @bgri in https://github.com/bgri/m100LE/issues/14#issuecomment-1219738541_

**Comment by hackerb9** [comment]
@bgri, Please run this version on your PC-8201A and let me know what the three byte encoding it prints out for BTNWR. Hopefully htis is just an off by one error. The bytes for REBUS should be `93`, `227`, `130`. If they all match, then perhaps, there is something funny about the way math is done on the NEC machines.  If none of the bytes match, then we have something more serious going on, like reading the address in memory incorrectly from the Ram Directory.

**Comment by bgri** [comment]
![IMGP0024](https://user-images.githubusercontent.com/14062627/186022713-3d750600-71f2-4006-9569-81f1ff420296.jpeg)
![IMGP0025](https://user-images.githubusercontent.com/14062627/186022728-88d0bfa6-858a-43f6-a7a0-8536b6847e1a.jpeg)

Hmmmm.

**Comment by hackerb9** [comment]
That's odd. There is an off by one error: the size should be 1098 bytes not 1097, but those bytes (195, 148, 124) don't appear anywhere in my copy of [WL2022.CO](https://github.com/hackerb9/M100LE/blob/2fa10eb1cab71be4ea2a3013e15ec1edfcf474dd/WL2022.CO).  

But, it clearly is somehow related to the file: the size is too close to be an accident. And any other .CO file would have the LOAD and START addresses set to something real, not zero.   

When I'm not so tired, I'll think about this more. In the meantime, can you verify that you have the same WL2022.CO file?

**Comment by hackerb9** [comment]
I figured it out. Your WL2022.CO file was not created correctly. The space for it was allocated using `BSAVE "WL2022.CO",0,1097` but the data was never actually poked into place. Perhaps there was a problem running CMPRSS?

The bytes we're seeing are simply a copy of the ROM that was made during the BSAVE. If you do 
```BASIC
? peek(0) peek(1) peek(2)`
```
I bet you'll see the same numbers (195,148, 124). 

The solution is to either run CMPRSS to create WL2022.CO from an existing WL2022.DO (on the NEC or on your computer via serial) or you can simply transfer the current [WL2022.CO](https://github.com/bgri/m100LE/raw/main/WL2022.CO) file to the NEC.

**Comment by bgri** [comment]
Yep, same numbers. Then transferred the version of WL2002.co from the previous comment and it works fine.
![image](https://user-images.githubusercontent.com/14062627/186991060-7b8ab0e5-f60a-4d3d-aeaf-63635a087041.png)

![image](https://user-images.githubusercontent.com/14062627/186990945-d1151bbe-2fde-4cf6-84d8-4c5dab7048a1.png)

So it was a badly-created .CO file. Good to know. And we have another success!

**Comment by hackerb9** [comment]
That's great! And the T102?

**Comment by hackerb9** [comment]
Hurray! Closing this issue as fixed.

**Comment by bgri** [comment]
As an additional comment. Part of the issue I had was when I attempted to remove WL2022.CO using the KILL command: `KILL WL2022.CO` the 102 would lock up. Also occurred when using TS-DOS to attempt removal or overwriting the file, though that time I heard the relay click. 

Of course, this meant a complete restart, configure TERM, read in TS-DOS.DO, Run/install TS-DOS, then read in M100LE.DO, save it, and read in WL2022.CO.  Good thing I like playing with these things :)

As for the deleting of the .CO file, something's fishy in the state of Denmark...

**Comment by hackerb9** [comment]
> As an additional comment. Part of the issue I had was when I attempted to remove WL2022.CO using the KILL command: `KILL WL2022.CO` the 102 would lock up. Also occurred when using TS-DOS to attempt removal or overwriting the file, though that time I heard the relay click.
> 
> Of course, this meant a complete restart, configure TERM, read in TS-DOS.DO, Run/install TS-DOS, then read in M100LE.DO, save it, and read in WL2022.CO. Good thing I like playing with these things :)
> 
> As for the deleting of the .CO file, something's fishy in the state of Denmark...

Yikes. I wonder if the fishy .CO file was created by an old version of my CMPRSS.BA program before I had added support for the T102. It would have created the file using SAVEM and then (if the program didn't check for errors like it does now), it would start trying to POKE data into the file. I wouldn't have thought that could be a problem as the file address would be zero, meaning it would be harmlessly POKEing into immutable ROM. 

I hate to make you the guinea pig, but would you mind trying the current version of [CMPRSS](https://github.com/bgri/m100LE/raw/main/CMPRSS.DO) on the Tandy 102 and see if it blows up?

**Comment by bgri** [comment]
> I hate to make you the guinea pig, but would you mind trying the current version of [CMPRSS](https://github.com/bgri/m100LE/raw/main/CMPRSS.DO) on the Tandy 102 and see if it blows up?

I love being a guinea pig -- I've got the hardware, may as well use it. I've added it to the top of my list.

**Comment by bgri** [comment]
Looks like that got it. New version of CMPRSS created WL2022.CO. Then Killed it from basic.
<img width="968" alt="image" src="https://user-images.githubusercontent.com/14062627/188990660-359ef68b-4321-49c6-84d8-39ee9652824f.png">
