### ISSUE TITLE
Do not assign to MID$() for NEC compatibility

### ISSUE THREAD

**Issue by hackerb9** [bgri/m100LE#25]
If what I remember from the N82 BASIC manual is correct, one cannot assign to the result of MID$() on the NEC PC-8201. For example, the following works under Tandy's BASIC but I believe it will fail on a NEC:

```basic
7341 IF MID$(H$,I,1) = MID$(TW$,I,1) THEN MID$(GW$,I,1) = MID$(TW$,I,1)
```

It looks like SO$, GW$, H$, A1$, A2$, and WF$ are written to this way. While there are workaround, it would be good to find a method which is not too verbose. Perhaps using an array of strings will work. 

Here are all the occurrences which I see in M100LE.DO right now:

```BASIC
5033 IF ASC(MID$(SO$(I),J,1))>=65 THEN MID$(SO$(I),J,1)="*"

7341 IF MID$(H$,I,1) = MID$(TW$,I,1) THEN MID$(GW$,I,1) = MID$(TW$,I,1)
7342 IF MID$(H$,I,1) = MID$(TW$,I,1) THEN MID$(H$,I,1) = "!" :CC=CC+1

7415 IF T<=13 THEN IF MID$(A1$,T,1) <> "*" THEN: IF MID$(TM$,I,1) = MID$(GW$,I,1) THEN MID$(A1$,T,1)="*" ELSE MID$(A1$,T,1)=MID$(GW$,I,1)
7420 IF T>13 THEN IF MID$(A2$,T-13,1) <> "*" THEN: IF MID$(TM$,I,1) = MID$(GW$,I,1) THEN MID$(A2$,T-13,1) = "*" ELSE MID$(A2$,T-13,1) = MID$(GW$,I,1)

8350 MID$(WF$,5) = RIGHT$(AD$,2): 'CREATE THE YEAR'S WORD FILE NAME FROM AD$    
```

**Comment by hackerb9** [comment]
It occurs to me that we could use `POKE` to write to strings if NEC's BASIC had `VARPTR()`. However, I am pretty sure it does not.

So another idea occurs to me. What if the program allocated a small data file in RAM just for temporarily holding variables. Since we already have the routine for finding a file's address in RAM storage, it should work easily and be cross platform. The only problem might be if the program doesn't exit cleanly and an ugly temp file is left behind in the directory. 

To allocate 64 bytes of memory:

```BASIC
10 IF ID=148 BSAVE "TMPFIL.CO", 0, 64 ELSE SAVEM "TMPFIL.CO",0,64
```

To access that memory:

```BASIC
20 WL$="TMPFIL.CO"
30 GOSUB 2000
40 TF=WA
50 IF (TF=0) OR (PEEK(TF+2)+256*PEEK(TF+3) != 64) THEN ERROR 6
60 TF=TF+6
70 A1=TF: A2=TF+5: WF=TF+10: SO=TF+16 [... etc ... ]
```

**Comment by bgri** [comment]
Neat! I like this solution :)

I was looking at item 9 on this page: https://www.web8201.net/m100nec.asp As a way around it... but I like your approach!

**Comment by hackerb9** [comment]
> Neat! I like this solution :)
> 
> I was looking at item 9 on this page: https://www.web8201.net/m100nec.asp As a way around it... but I like your approach!

Yeah, item 9 is a bit ugly looking, though I'm not confident using a temp file for string storage won't be even uglier. 

Another possible solution: Item 5 gives a VARPTR implementation which might (or might not) be cleaner.  I believe VARPTR allows one to get the memory address of a string and manipulate it.

Pros: 
* Strings are strings and can be printed as such.
* No worry about accidentally leaving a temp file behind.
Cons:
* Perhaps less portable than a RAM directory
  * Written in machine code
  * Does this code work on _all_ NEC models?
  * Does VARPTR exist on all other Kyotronic computers?
* the machine code may be too confusing to try to use or debug.
* Requires treating NEC computers differently.

**Comment by bgri** [comment]
Hmm, still more of a workaround for the NEC. Would be nice to use the tempfile or, how much room do we need? There is room in the LCD buffer RAM that's accessible. Basically 20 bytes (if my math is right) of display RAM that's outside the LCD viewing area, but is addressable.
![image](https://user-images.githubusercontent.com/14062627/186988087-97b3a8cc-8447-4eea-b45d-3956b67f2545.png)

P. 154-155 from the [NEC Technical Reference](https://www.web8201.net/Files/LIBRARY_web8201/NEC8201A-TechRef.pdf)

**Comment by hackerb9** [comment]
LCD buffer sounds like a cool trick, but probably is not very portable. Also, the code for getting the data in and out might be kind of ugly. 

I've been thinking more about using a data file in the RAM Directory as a way of allocating storage and I realized that the data in there would persist if M100LE didn't delete it. Meaning, if you want to keep track of a streak or have a histogram of results, that would be easy to do.

On the other hand, POKEing and PEEKing data is not the most elegant way to be addressing the bytes of string. Particularly when it comes time to print the string, instead of simply printing it, we'd need something like:

```BASIC
FOR T = X TO X+5
  PRINT CHR$(PEEK(T));
NEXT T
```

It might make sense to instead use an array of characters. Such as A1$(1)="A": A1$(2)="B": A1$(3)="C"...  That could be the most portable and probably wouldn't be too slow for manipulating and printing the variables.
