### ISSUE TITLE
Olivetti M10 support

### ISSUE THREAD

**Issue by hackerb9** [bgri/m100LE#41]
Tried running the code on Virtual T's emulated M10 device and it gives a ?DS error just from running the program. Doing "CLEAR 512" seems to solve the problem. Of course, we'll need the Ram Directory address for this machine (35) `as` well.

**Comment by bgri** [comment]
For sure. Looks like there's much less documentation online for it than the others. I've not seen a service manual yet.  Best I could find is this memory map in an [Italian 3rd party 'how to' book](https://archive.org/details/olivettim10guidaalluso/page/n187/mode/2up). pp 186

**Comment by hackerb9** [comment]
Thanks for the memory map, that gives me the location of the RAM Directory, which was the main hurdle I foresaw.

What I didn't see coming was that the DATE$ is neither in Tandy (MM/DD/YY) nor NEC (YY/MM/DD) format. It is DD/MM/YY! Was that the Italian standard? 

The date parsing code was already getting ugly from handling two formats. I'll refactor it to clean it up.

**Comment by hackerb9** [comment]
A-ha! It's not just Italy. This is (was?) the normal European format. 

![Middle Endian](https://user-images.githubusercontent.com/10174223/198160134-8356ca1d-4231-4f9a-b003-537b1621d637.png)

And what we were calling "European" format, NEC's YY/MM/DD, is most similar the ISO 8601 standard. (Which does appear to be popular in Europe now.)

![ISO 8601 was published on 06/05/88 and most recently amended on 12/01/04.](https://user-images.githubusercontent.com/10174223/198160886-9ab56ff4-66f5-4f19-9baa-750ac7bcb3bc.png)
 
And, finally, if you want to know how this relates to little-endian holy egg wars:

https://www.todayifoundout.com/index.php/2014/10/americans-write-dates-differently-practically-everyone-else-relates-data-storage-holy-wars-soft-boiled-eggs/

**Comment by bgri** [comment]
That was a good read, thanks! I like to break my eggs in the middle :), but prefer my dates little-endian.

**Comment by hackerb9** [comment]
If you prefer little-endian dates, then try out my [Olivetti branch](https://github.com/hackerb9/M100LE/tree/olivetti) in VirtualT's M10 emulation. I'm still checking it for bugs, but it does appear to be working now.

**Comment by bgri** [comment]
Just a minor preference. Little to big, as it were. Though given the Canadian context (do we use American or British?) Bigendian makes more sense from an immediately understandable perspective. 2022/02/02, I would assume to be Feb second. 'Cause why else would you stick that big-ol' date on front unless you were describing bigger to smaller.

Gotta love the way culture influences things. Nothing to do with logic :)
