### ISSUE TITLE
January is the same as February

### ISSUE THREAD

**Issue by hackerb9** [bgri/m100LE#7]
Line 8335 is incorrect as it presumes that a FOR loop from 1 to 0 will run zero times. That is true in C, but in BASIC it runs once. The result is that the puzzle for January 1st is for ordinal date 32, the same as February 1st.

Current buggy line:
```BASIC
8335 IF RF<>1 THEN:FOR I = 1 TO CM-1: DY=DY+DA(I): NEXT I: DY=DY+VAL(MID$(AD$,4,2))
```

Fixed code:
```BASIC
8355 IF RF<>1 AND CM>1 THEN: FOR I = 1 TO CM-1: DY=DY+DA(I): NEXT I
8337 IF RF<>1 THEN: DY=DY+VAL(MID$(AD$,4,2))
```

**Comment by bgri** [comment]
Interesting! Thanks again. I'll review this as soon as I can get to my gear... still recovering from moving :)
